### ISSUE TITLE
Function convertToEmoji() breaks on regex

### ISSUE THREAD

**Issue by Atulin** [imfunniee/gitfolio#20]
```
$ node build name --atulin
E:\Software\Laragon\www\gitfolio\populate.js:12
    if(text.match(/(?<=:\s*).*?(?=\s*:)/gs) != null){
                  ^

SyntaxError: Invalid regular expression flags
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Software\Laragon\www\gitfolio\build.js:3:22)
```

**Comment by Atulin** [comment]
Thought it was me being dumb with `name --atulin`, instead of `--name atulin`, but no, breaks on either.

```
$ node build --name atulin
E:\Software\Laragon\www\gitfolio\populate.js:12
    if(text.match(/(?<=:\s*).*?(?=\s*:)/gs) != null){
                  ^

SyntaxError: Invalid regular expression flags
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Software\Laragon\www\gitfolio\build.js:3:22)
```

**Comment by imfunniee** [comment]
hmm works for me, could you try it from scratch, like fresh clone.

![hmm](https://user-images.githubusercontent.com/36105478/57978391-b37c6580-7a2a-11e9-95af-3d46711024c5.PNG)

**Comment by Atulin** [comment]
That was a fresh clone. Cloned it again, same issue.

```
$ node -v
v8.9.0

$ npm -v
6.8.0
```

**Comment by imfunniee** [comment]
i tested this on node version `v10.15.1` and it works fine, could you try upgrading your node.  [similar issue here](https://github.com/infinitered/ignite/issues/1371#issuecomment-459151865)

**Comment by Atulin** [comment]
Updated Node to 10.15.3 and it works perfectly fine now. Can be closed 👌

**Comment by imfunniee** [comment]
nice 👌

**Comment by blesson3** [comment]
Same issue, also works with 
```
10:18:40 ~/.../gitfolio master$ node --version
v12.3.0
```
