### ISSUE TITLE
Can't build: HTTPError: Response code 403

### ISSUE THREAD

**Issue by Lancern** [imfunniee/gitfolio#44]
<details>
<summary>System Information</summary>

| Name            | Value                                                          |
| --------------- | -------------------------------------------------------------- |
| OS              | macOS Mojave (10.14.3)                                              |
| Node Version    | v10.15.3                           |
| Project Version | 911a23c |

</details>

<details>
<summary>What is the current behavior?</summary>

Node can't build the repository due to an unexpected HTTP 403 status code emitted at ```EventEmitter.emitter.on``` in file ```node_modules/got/source/as-promise.js:74:19```.

Command line used to build the repository: ```node build --name Lancern```

Files in ```dist/``` after executing the build command:
* blog.json
* config.json
* index.css

Output of the build command is attached in the Logs part.

</details>

<details>
<summary>What is the expected behavior?</summary>

The ```npm build``` should succeed and eventually generate an ```index.html``` file under the ```dist/``` directory.

</details>

<details>
<summary>Logs</summary>

Output of ```npm build```:
```
Building HTML/CSS...
{ HTTPError: Response code 403 (Forbidden)
    at EventEmitter.emitter.on (/Users/lancern/Documents/Development/Source/gitfolio/node_modules/got/source/as-promise.js:74:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HTTPError',
  host: 'api.github.com',
  hostname: 'api.github.com',
  method: 'GET',
  path: '/users/Lancern/repos?sort=created&order=asc&per_page=1200',
  socketPath: undefined,
  protocol: 'https:',
  url:
   'https://api.github.com/users/Lancern/repos?sort=created&order=asc&per_page=1200',
  gotOptions:
   { path: '/users/Lancern/repos?sort=created&order=asc&per_page=1200',
     protocol: 'https:',
     slashes: true,
     auth: null,
     host: 'api.github.com',
     port: null,
     hostname: 'api.github.com',
     hash: null,
     search: '?sort=created&order=asc&per_page=1200',
     pathname: '/users/Lancern/repos',
     href:
      'https://api.github.com/users/Lancern/repos?sort=created&order=asc&per_page=1200',
     retry:
      { retries: [Function],
        methods: [Set],
        statusCodes: [Set],
        errorCodes: [Set] },
     headers:
      { 'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
        'accept-encoding': 'gzip, deflate' },
     hooks:
      { beforeRequest: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: [],
        beforeError: [],
        init: [] },
     decompress: true,
     throwHttpErrors: true,
     followRedirect: true,
     stream: false,
     form: false,
     json: false,
     cache: false,
     useElectronNet: false,
     method: 'GET' },
  statusCode: 403,
  statusMessage: 'Forbidden',
  headers:
   { date: 'Tue, 21 May 2019 04:27:32 GMT',
     'content-type': 'application/json; charset=utf-8',
     'transfer-encoding': 'chunked',
     connection: 'close',
     server: 'GitHub.com',
     status: '403 Forbidden',
     'x-ratelimit-limit': '60',
     'x-ratelimit-remaining': '0',
     'x-ratelimit-reset': '1558413235',
     'x-github-media-type': 'github.v3; format=json',
     'access-control-expose-headers':
      'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type',
     'access-control-allow-origin': '*',
     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
     'x-frame-options': 'deny',
     'x-content-type-options': 'nosniff',
     'x-xss-protection': '1; mode=block',
     'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
     'content-security-policy': 'default-src \'none\'',
     'content-encoding': 'gzip',
     'x-github-request-id': 'lol' },
  body:
   '{"message":"API rate limit exceeded for `dude your ip was here` (But here\'s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}' }
```

Should I configure something to make the build process work?

</details>

**Comment by imfunniee** [comment]
You reached the github's api limit, check here when it resets https://api.github.com/rate_limit. More about it here https://developer.github.com/v3/#rate-limiting

Also don't just blindly paste log lol, it had your ip. i removed it no worries but please be careful in future.
