### ISSUE TITLE
Build breaks with emojis in personal description

### ISSUE THREAD

**Issue by lmammino** [imfunniee/gitfolio#6]
Error:

```
Building HTML/CSS...
Error: Emoji named '//amzn.to/2a418Q2 - maintainer of https' not found
    at Object.of (.../gitfolio/node_modules/github-emoji/index.js:96:15)
    at convertToEmoji (.../gitfolio/build.js:55:28)
    at .../gitfolio/build.js:102:56
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

How to reproduce:

```bash
git clone https://github.com/imfunniee/gitfolio.git
cd gitfolio
npm i
node build --name lmammino
```

**Comment by imfunniee** [comment]
fixed it 👌

**Comment by lmammino** [comment]
Thanks :)
