### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by AyraHikari** [imfunniee/gitfolio#87]
<details>
<summary>System Information</summary>

| Name            | Value                                                          |
| --------------- | -------------------------------------------------------------- |
| OS              | Linux Ubuntu 16.04                                |
| Node Version    | v4.2.6                           |
| Project Version | 4a28721 |

</details>

<details>
<summary>What is the current behavior?</summary>
After install with `npm i gitfolio -g`, and then run `gitfolio build AyraHikari` i got this error
</details>

<details>
<summary>What is the expected behavior?</summary>
Build this project
</details>

<details>
<summary>Logs</summary>

```
root@Ayra:~/gitfolio# gitfolio build AyraHikari
/root/gitfolio/build.js:9
const { updateHTML } = require('./populate');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```

</details>

**Comment by AyraHikari** [comment]
Fixed, just update Nodejs to latest version.

```
curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt-get install nodejs
```

`nodejs -v`
> v8.16.0
